sudo: false

language: go
go:
  - "1.10"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -u github.com/golang/lint/golint
  - go get github.com/mitchellh/gox
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
  - dep ensure
  - golint $(go list ./... | grep -v /vendor/)
  - go vet ./...
  - go test -cover ./...
  - go test -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT

before_deploy:
  - gox -os "linux darwin" -arch "386 amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/double-team/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true


notifications:
  email:
    on_success: never
    on_failure: always