sudo: false

language: go
go:
  - "1.13"
  - "1.x"
env:
  - GO111MODULE=on

before_install:
  - go get -u golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - golint ./...
  - go vet ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-pro

before_deploy:
  - gox -os "linux darwin" -arch "386 amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/double-team/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true


notifications:
  email:
    on_success: never
    on_failure: always