sudo: false

language: go
go:
  - 1.10

before_install:
  - go get -u github.com/golang/dep/cmd/dep github.com/golang/lint/golint
  - go get github.com/mitchellh/gox
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - dep ensure
  - golint $(go list ./... | grep -v /vendor/)
  - go vet ./...
  - go test -cover ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci

before_deploy:
  - gox -os "linux darwin" -arch "386 amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/double-team/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true


notifications:
  email:
    on_success: never
    on_failure: always